name: Shellcheck
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: |
        shellcheck pfetch
        sh pfetch
        var=$(printf '[?7l[?25l')
        echo "a${var}b"
