name: Shellcheck
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: |
        shellcheck pfetch
        sh pfetch
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: sh pfetch
